[phases.setup]
nixPkgs = ['...', 'nodejs_18']

[phases.install]
dependsOn = ['setup']
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[phases.build]
dependsOn = ['install']
cmds = [
    'php artisan config:clear',
    'php artisan route:clear',
    'php artisan view:clear'
]

[start]
cmd = 'bash startup.sh'
